name: Build App
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Build Application
        run: |
          xcodebuild -project OpenWallpaperEngine.xcodeproj -scheme "Open Wallpaper Engine" -configuration Release -derivedDataPath build_output

      - name: Upload Zip
        uses: actions/upload-artifact@v4
        with:
          name: Open-Wallpaper-Engine-App
          path: build_output/Build/Products/Release/Open Wallpaper Engine.app
